[workspace]
resolver = "2"
members = ["agent", "core", "relay"]

[workspace.package]
version = "0.2.1"
edition = "2021"
rust-version = "1.83.0"
license = "MIT"
repository = "https://github.com/nasa42/webterm"

[profile.release]
lto = true
